// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database_token_mysql

type Jtiiat struct {
	Jti           string
	MinIat        int64
	MinRefreshIat int64
}

type Subjectiat struct {
	Subject       string
	MinIat        int64
	MinRefreshIat int64
}
