// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subjectIAT.sql

package database_token_mysql

import (
	"context"
	"database/sql"
)

const addSubjectEntry = `-- name: AddSubjectEntry :execresult
INSERT INTO subjectIAT (subject, min_iat, min_refresh_iat) VALUES (?, ? ,?)
`

type AddSubjectEntryParams struct {
	Subject       string
	MinIat        int64
	MinRefreshIat int64
}

func (q *Queries) AddSubjectEntry(ctx context.Context, arg AddSubjectEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addSubjectEntry, arg.Subject, arg.MinIat, arg.MinRefreshIat)
}

const getMinIAT = `-- name: GetMinIAT :one
SELECT min_iat FROM subjectIAT WHERE subject = ? LIMIT 1
`

func (q *Queries) GetMinIAT(ctx context.Context, subject string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMinIAT, subject)
	var min_iat int64
	err := row.Scan(&min_iat)
	return min_iat, err
}

const getMinIATRefreshIAT = `-- name: GetMinIATRefreshIAT :one
SELECT min_iat, min_refresh_iat FROM subjectIAT WHERE subject = ? LIMIT 1
`

type GetMinIATRefreshIATRow struct {
	MinIat        int64
	MinRefreshIat int64
}

func (q *Queries) GetMinIATRefreshIAT(ctx context.Context, subject string) (GetMinIATRefreshIATRow, error) {
	row := q.db.QueryRowContext(ctx, getMinIATRefreshIAT, subject)
	var i GetMinIATRefreshIATRow
	err := row.Scan(&i.MinIat, &i.MinRefreshIat)
	return i, err
}

const getMinRefreshIAT = `-- name: GetMinRefreshIAT :one
SELECT min_refresh_iat FROM subjectIAT WHERE subject = ? LIMIT 1
`

func (q *Queries) GetMinRefreshIAT(ctx context.Context, subject string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMinRefreshIAT, subject)
	var min_refresh_iat int64
	err := row.Scan(&min_refresh_iat)
	return min_refresh_iat, err
}

const removeSubjectEntry = `-- name: RemoveSubjectEntry :execresult
DELETE FROM subjectIAT WHERE subject = ?
`

func (q *Queries) RemoveSubjectEntry(ctx context.Context, subject string) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeSubjectEntry, subject)
}

const updateSubjectMinIAT = `-- name: UpdateSubjectMinIAT :execresult
UPDATE subjectIAT SET min_iat = ? WHERE subject = ?
`

type UpdateSubjectMinIATParams struct {
	MinIat  int64
	Subject string
}

func (q *Queries) UpdateSubjectMinIAT(ctx context.Context, arg UpdateSubjectMinIATParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSubjectMinIAT, arg.MinIat, arg.Subject)
}

const updateSubjectMinRefreshIAT = `-- name: UpdateSubjectMinRefreshIAT :execresult
UPDATE subjectIAT SET min_iat = ?, min_refresh_iat = ?  WHERE subject = ?
`

type UpdateSubjectMinRefreshIATParams struct {
	MinIat        int64
	MinRefreshIat int64
	Subject       string
}

func (q *Queries) UpdateSubjectMinRefreshIAT(ctx context.Context, arg UpdateSubjectMinRefreshIATParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSubjectMinRefreshIAT, arg.MinIat, arg.MinRefreshIat, arg.Subject)
}
