// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accounts.sql

package database

import (
	"context"
	"database/sql"
)

const addAccount = `-- name: AddAccount :execresult
INSERT INTO mailshadow (username, password, allow_pwd_chng) VALUES (?, ?, 'true')
`

type AddAccountParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) AddAccount(ctx context.Context, arg AddAccountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addAccount, arg.Username, arg.Password)
}

const addMasterAccount = `-- name: AddMasterAccount :execresult
INSERT INTO mailmaster (username, password, active) VALUES (?, ?, 'false')
`

type AddMasterAccountParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) AddMasterAccount(ctx context.Context, arg AddMasterAccountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addMasterAccount, arg.Username, arg.Password)
}

const addProtectedReceive = `-- name: AddProtectedReceive :execresult
INSERT INTO receiveProtectMap (address, access, active) VALUES (?, ?, 'false')
`

type AddProtectedReceiveParams struct {
	Address string `json:"address"`
	Access  string `json:"access"`
}

func (q *Queries) AddProtectedReceive(ctx context.Context, arg AddProtectedReceiveParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addProtectedReceive, arg.Address, arg.Access)
}

const changePassword = `-- name: ChangePassword :execresult
UPDATE mailshadow SET password = ? WHERE username = ? AND allow_pwd_chng = 'true'
`

type ChangePasswordParams struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, changePassword, arg.Password, arg.Username)
}

const disableAccountPasswordChange = `-- name: DisableAccountPasswordChange :execresult
UPDATE mailshadow SET allow_pwd_chng = 'false' WHERE username = ?
`

func (q *Queries) DisableAccountPasswordChange(ctx context.Context, username string) (sql.Result, error) {
	return q.db.ExecContext(ctx, disableAccountPasswordChange, username)
}

const disableMasterAccount = `-- name: DisableMasterAccount :execresult
UPDATE mailmaster SET active = 'false' WHERE username = ?
`

func (q *Queries) DisableMasterAccount(ctx context.Context, username string) (sql.Result, error) {
	return q.db.ExecContext(ctx, disableMasterAccount, username)
}

const disableProtectedReceive = `-- name: DisableProtectedReceive :execresult
UPDATE receiveProtectMap SET active = 'false' WHERE address = ?
`

func (q *Queries) DisableProtectedReceive(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, disableProtectedReceive, address)
}

const enableAccountPasswordChange = `-- name: EnableAccountPasswordChange :execresult
UPDATE mailshadow SET allow_pwd_chng = 'true' WHERE username = ?
`

func (q *Queries) EnableAccountPasswordChange(ctx context.Context, username string) (sql.Result, error) {
	return q.db.ExecContext(ctx, enableAccountPasswordChange, username)
}

const enableMasterAccount = `-- name: EnableMasterAccount :execresult
UPDATE mailmaster SET active = 'true' WHERE username = ?
`

func (q *Queries) EnableMasterAccount(ctx context.Context, username string) (sql.Result, error) {
	return q.db.ExecContext(ctx, enableMasterAccount, username)
}

const enableProtectedReceive = `-- name: EnableProtectedReceive :execresult
UPDATE receiveProtectMap SET active = 'true' WHERE address = ?
`

func (q *Queries) EnableProtectedReceive(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, enableProtectedReceive, address)
}

const getAccount = `-- name: GetAccount :one
SELECT username, password, allow_pwd_chng FROM mailshadow WHERE username = ? LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, username string) (Mailshadow, error) {
	row := q.db.QueryRowContext(ctx, getAccount, username)
	var i Mailshadow
	err := row.Scan(&i.Username, &i.Password, &i.AllowPwdChng)
	return i, err
}

const getAccountAllowPasswordChange = `-- name: GetAccountAllowPasswordChange :one
SELECT allow_pwd_chng FROM mailshadow WHERE username = ? LIMIT 1
`

func (q *Queries) GetAccountAllowPasswordChange(ctx context.Context, username string) (MailshadowAllowPwdChng, error) {
	row := q.db.QueryRowContext(ctx, getAccountAllowPasswordChange, username)
	var allow_pwd_chng MailshadowAllowPwdChng
	err := row.Scan(&allow_pwd_chng)
	return allow_pwd_chng, err
}

const getAllAccounts = `-- name: GetAllAccounts :many
SELECT username, password, allow_pwd_chng FROM mailshadow
`

func (q *Queries) GetAllAccounts(ctx context.Context) ([]Mailshadow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mailshadow
	for rows.Next() {
		var i Mailshadow
		if err := rows.Scan(&i.Username, &i.Password, &i.AllowPwdChng); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllActiveMasterAccounts = `-- name: GetAllActiveMasterAccounts :many
SELECT username, password FROM mailmaster WHERE active = 'true'
`

type GetAllActiveMasterAccountsRow struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) GetAllActiveMasterAccounts(ctx context.Context) ([]GetAllActiveMasterAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveMasterAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActiveMasterAccountsRow
	for rows.Next() {
		var i GetAllActiveMasterAccountsRow
		if err := rows.Scan(&i.Username, &i.Password); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllActiveProtectedReceives = `-- name: GetAllActiveProtectedReceives :many
SELECT address, access FROM receiveProtectMap WHERE active = 'true'
`

type GetAllActiveProtectedReceivesRow struct {
	Address string `json:"address"`
	Access  string `json:"access"`
}

func (q *Queries) GetAllActiveProtectedReceives(ctx context.Context) ([]GetAllActiveProtectedReceivesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveProtectedReceives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActiveProtectedReceivesRow
	for rows.Next() {
		var i GetAllActiveProtectedReceivesRow
		if err := rows.Scan(&i.Address, &i.Access); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllInactiveMasterAccounts = `-- name: GetAllInactiveMasterAccounts :many
SELECT username, password FROM mailmaster WHERE active <> 'true'
`

type GetAllInactiveMasterAccountsRow struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) GetAllInactiveMasterAccounts(ctx context.Context) ([]GetAllInactiveMasterAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllInactiveMasterAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllInactiveMasterAccountsRow
	for rows.Next() {
		var i GetAllInactiveMasterAccountsRow
		if err := rows.Scan(&i.Username, &i.Password); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllInactiveProtectedReceives = `-- name: GetAllInactiveProtectedReceives :many
SELECT address, access FROM receiveProtectMap WHERE active <> 'true'
`

type GetAllInactiveProtectedReceivesRow struct {
	Address string `json:"address"`
	Access  string `json:"access"`
}

func (q *Queries) GetAllInactiveProtectedReceives(ctx context.Context) ([]GetAllInactiveProtectedReceivesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllInactiveProtectedReceives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllInactiveProtectedReceivesRow
	for rows.Next() {
		var i GetAllInactiveProtectedReceivesRow
		if err := rows.Scan(&i.Address, &i.Access); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMasterAccounts = `-- name: GetAllMasterAccounts :many
SELECT username, password, active FROM mailmaster
`

func (q *Queries) GetAllMasterAccounts(ctx context.Context) ([]Mailmaster, error) {
	rows, err := q.db.QueryContext(ctx, getAllMasterAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mailmaster
	for rows.Next() {
		var i Mailmaster
		if err := rows.Scan(&i.Username, &i.Password, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProtectedReceives = `-- name: GetAllProtectedReceives :many
SELECT address, access, active FROM receiveProtectMap
`

func (q *Queries) GetAllProtectedReceives(ctx context.Context) ([]Receiveprotectmap, error) {
	rows, err := q.db.QueryContext(ctx, getAllProtectedReceives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receiveprotectmap
	for rows.Next() {
		var i Receiveprotectmap
		if err := rows.Scan(&i.Address, &i.Access, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMasterAccount = `-- name: GetMasterAccount :one
SELECT username, password, active FROM mailmaster WHERE username = ? LIMIT 1
`

func (q *Queries) GetMasterAccount(ctx context.Context, username string) (Mailmaster, error) {
	row := q.db.QueryRowContext(ctx, getMasterAccount, username)
	var i Mailmaster
	err := row.Scan(&i.Username, &i.Password, &i.Active)
	return i, err
}

const getPassword = `-- name: GetPassword :one
SELECT password FROM mailshadow WHERE username = ? LIMIT 1
`

func (q *Queries) GetPassword(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPassword, username)
	var password string
	err := row.Scan(&password)
	return password, err
}

const getProtectedReceive = `-- name: GetProtectedReceive :one
SELECT address, access, active FROM receiveProtectMap WHERE address = ? LIMIT 1
`

func (q *Queries) GetProtectedReceive(ctx context.Context, address string) (Receiveprotectmap, error) {
	row := q.db.QueryRowContext(ctx, getProtectedReceive, address)
	var i Receiveprotectmap
	err := row.Scan(&i.Address, &i.Access, &i.Active)
	return i, err
}

const removeAccount = `-- name: RemoveAccount :execresult
DELETE FROM mailshadow WHERE username = ?
`

func (q *Queries) RemoveAccount(ctx context.Context, username string) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeAccount, username)
}

const removeMasterAccount = `-- name: RemoveMasterAccount :execresult
DELETE FROM mailmaster WHERE username = ?
`

func (q *Queries) RemoveMasterAccount(ctx context.Context, username string) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeMasterAccount, username)
}

const removeProtectedReceive = `-- name: RemoveProtectedReceive :execresult
DELETE FROM receiveProtectMap WHERE address = ?
`

func (q *Queries) RemoveProtectedReceive(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeProtectedReceive, address)
}
