// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: aliases.sql

package database

import (
	"context"
	"database/sql"
)

const addAlias = `-- name: AddAlias :execresult
INSERT INTO aliasMap (address, goto, active, etype) VALUES (? , ?, 'true', 'plain')
`

type AddAliasParams struct {
	Address string `json:"address"`
	Goto    string `json:"goto"`
}

func (q *Queries) AddAlias(ctx context.Context, arg AddAliasParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addAlias, arg.Address, arg.Goto)
}

const addAliasLike = `-- name: AddAliasLike :execresult
INSERT INTO aliasMap (address, goto, active, etype) VALUES (? , ?, 'true', 'like')
`

type AddAliasLikeParams struct {
	Address string `json:"address"`
	Goto    string `json:"goto"`
}

func (q *Queries) AddAliasLike(ctx context.Context, arg AddAliasLikeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addAliasLike, arg.Address, arg.Goto)
}

const addAliasRegex = `-- name: AddAliasRegex :execresult
INSERT INTO aliasMap (address, goto, active, etype) VALUES (? , ?, 'true', 'regex')
`

type AddAliasRegexParams struct {
	Address string `json:"address"`
	Goto    string `json:"goto"`
}

func (q *Queries) AddAliasRegex(ctx context.Context, arg AddAliasRegexParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addAliasRegex, arg.Address, arg.Goto)
}

const addDomainAlias = `-- name: AddDomainAlias :execresult
INSERT INTO aliasdomainMap (domain, goto, active, etype) VALUES (? , ?, 'true', 'plain')
`

type AddDomainAliasParams struct {
	Domain string `json:"domain"`
	Goto   string `json:"goto"`
}

func (q *Queries) AddDomainAlias(ctx context.Context, arg AddDomainAliasParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addDomainAlias, arg.Domain, arg.Goto)
}

const addDomainAliasLike = `-- name: AddDomainAliasLike :execresult
INSERT INTO aliasdomainMap (domain, goto, active, etype) VALUES (? , ?, 'true', 'like')
`

type AddDomainAliasLikeParams struct {
	Domain string `json:"domain"`
	Goto   string `json:"goto"`
}

func (q *Queries) AddDomainAliasLike(ctx context.Context, arg AddDomainAliasLikeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addDomainAliasLike, arg.Domain, arg.Goto)
}

const addDomainAliasRegex = `-- name: AddDomainAliasRegex :execresult
INSERT INTO aliasdomainMap (domain, goto, active, etype) VALUES (? , ?, 'true', 'regex')
`

type AddDomainAliasRegexParams struct {
	Domain string `json:"domain"`
	Goto   string `json:"goto"`
}

func (q *Queries) AddDomainAliasRegex(ctx context.Context, arg AddDomainAliasRegexParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addDomainAliasRegex, arg.Domain, arg.Goto)
}

const addSenderAlias = `-- name: AddSenderAlias :execresult
INSERT INTO senderaliasMap (address, allowed, active) VALUES (? , ?, 'true')
`

type AddSenderAliasParams struct {
	Address string `json:"address"`
	Allowed string `json:"allowed"`
}

func (q *Queries) AddSenderAlias(ctx context.Context, arg AddSenderAliasParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addSenderAlias, arg.Address, arg.Allowed)
}

const addUserAlias = `-- name: AddUserAlias :execresult
INSERT INTO aliasuserMap (user, goto, active, etype) VALUES (? , ?, 'true', 'plain')
`

type AddUserAliasParams struct {
	User string `json:"user"`
	Goto string `json:"goto"`
}

func (q *Queries) AddUserAlias(ctx context.Context, arg AddUserAliasParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addUserAlias, arg.User, arg.Goto)
}

const addUserAliasLike = `-- name: AddUserAliasLike :execresult
INSERT INTO aliasuserMap (user, goto, active, etype) VALUES (? , ?, 'true', 'like')
`

type AddUserAliasLikeParams struct {
	User string `json:"user"`
	Goto string `json:"goto"`
}

func (q *Queries) AddUserAliasLike(ctx context.Context, arg AddUserAliasLikeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addUserAliasLike, arg.User, arg.Goto)
}

const addUserAliasRegex = `-- name: AddUserAliasRegex :execresult
INSERT INTO aliasuserMap (user, goto, active, etype) VALUES (? , ?, 'true', 'regex')
`

type AddUserAliasRegexParams struct {
	User string `json:"user"`
	Goto string `json:"goto"`
}

func (q *Queries) AddUserAliasRegex(ctx context.Context, arg AddUserAliasRegexParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addUserAliasRegex, arg.User, arg.Goto)
}

const addWildcardAlias = `-- name: AddWildcardAlias :execresult
INSERT INTO wildcardaliasMap (address, goto, active) VALUES (? , ?, 'true')
`

type AddWildcardAliasParams struct {
	Address string `json:"address"`
	Goto    string `json:"goto"`
}

func (q *Queries) AddWildcardAlias(ctx context.Context, arg AddWildcardAliasParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addWildcardAlias, arg.Address, arg.Goto)
}

const changeAliasRedirect = `-- name: ChangeAliasRedirect :execresult
UPDATE aliasMap SET goto = ? WHERE address = ?
`

type ChangeAliasRedirectParams struct {
	Goto    string `json:"goto"`
	Address string `json:"address"`
}

func (q *Queries) ChangeAliasRedirect(ctx context.Context, arg ChangeAliasRedirectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, changeAliasRedirect, arg.Goto, arg.Address)
}

const changeDomainAliasRedirect = `-- name: ChangeDomainAliasRedirect :execresult
UPDATE aliasdomainMap SET goto = ? WHERE domain = ?
`

type ChangeDomainAliasRedirectParams struct {
	Goto   string `json:"goto"`
	Domain string `json:"domain"`
}

func (q *Queries) ChangeDomainAliasRedirect(ctx context.Context, arg ChangeDomainAliasRedirectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, changeDomainAliasRedirect, arg.Goto, arg.Domain)
}

const changeUserAliasRedirect = `-- name: ChangeUserAliasRedirect :execresult
UPDATE aliasuserMap SET goto = ? WHERE user = ?
`

type ChangeUserAliasRedirectParams struct {
	Goto string `json:"goto"`
	User string `json:"user"`
}

func (q *Queries) ChangeUserAliasRedirect(ctx context.Context, arg ChangeUserAliasRedirectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, changeUserAliasRedirect, arg.Goto, arg.User)
}

const changeWildcardAliasRedirect = `-- name: ChangeWildcardAliasRedirect :execresult
UPDATE wildcardaliasMap SET goto = ? WHERE address = ?
`

type ChangeWildcardAliasRedirectParams struct {
	Allowed string `json:"allowed"`
	Address string `json:"address"`
}

func (q *Queries) ChangeWildcardAliasRedirect(ctx context.Context, arg ChangeWildcardAliasRedirectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, changeWildcardAliasRedirect, arg.Allowed, arg.Address)
}

const disableAlias = `-- name: DisableAlias :execresult
UPDATE aliasMap SET active = 'true' WHERE address = ?
`

func (q *Queries) DisableAlias(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, disableAlias, address)
}

const disableDomainAlias = `-- name: DisableDomainAlias :execresult
UPDATE aliasdomainMap SET active = 'true' WHERE domain = ?
`

func (q *Queries) DisableDomainAlias(ctx context.Context, domain string) (sql.Result, error) {
	return q.db.ExecContext(ctx, disableDomainAlias, domain)
}

const disableSenderAlias = `-- name: DisableSenderAlias :execresult
UPDATE senderaliasMap SET active = 'true' WHERE ? AND allowed = ?
`

type DisableSenderAliasParams struct {
	Address interface{} `json:"address"`
	Allowed string      `json:"allowed"`
}

func (q *Queries) DisableSenderAlias(ctx context.Context, arg DisableSenderAliasParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, disableSenderAlias, arg.Address, arg.Allowed)
}

const disableUserAlias = `-- name: DisableUserAlias :execresult
UPDATE aliasuserMap SET active = 'true' WHERE user = ?
`

func (q *Queries) DisableUserAlias(ctx context.Context, user string) (sql.Result, error) {
	return q.db.ExecContext(ctx, disableUserAlias, user)
}

const disableWildcardAlias = `-- name: DisableWildcardAlias :execresult
UPDATE wildcardaliasMap SET active = 'true' WHERE address = ?
`

func (q *Queries) DisableWildcardAlias(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, disableWildcardAlias, address)
}

const enableAlias = `-- name: EnableAlias :execresult
UPDATE aliasMap SET active = 'true' WHERE address = ?
`

func (q *Queries) EnableAlias(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, enableAlias, address)
}

const enableDomainAlias = `-- name: EnableDomainAlias :execresult
UPDATE aliasdomainMap SET active = 'true' WHERE domain = ?
`

func (q *Queries) EnableDomainAlias(ctx context.Context, domain string) (sql.Result, error) {
	return q.db.ExecContext(ctx, enableDomainAlias, domain)
}

const enableSenderAlias = `-- name: EnableSenderAlias :execresult
UPDATE senderaliasMap SET active = 'true' WHERE ? AND allowed = ?
`

type EnableSenderAliasParams struct {
	Address interface{} `json:"address"`
	Allowed string      `json:"allowed"`
}

func (q *Queries) EnableSenderAlias(ctx context.Context, arg EnableSenderAliasParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, enableSenderAlias, arg.Address, arg.Allowed)
}

const enableUserAlias = `-- name: EnableUserAlias :execresult
UPDATE aliasuserMap SET active = 'true' WHERE user = ?
`

func (q *Queries) EnableUserAlias(ctx context.Context, user string) (sql.Result, error) {
	return q.db.ExecContext(ctx, enableUserAlias, user)
}

const enableWildcardAlias = `-- name: EnableWildcardAlias :execresult
UPDATE wildcardaliasMap SET active = 'true' WHERE address = ?
`

func (q *Queries) EnableWildcardAlias(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, enableWildcardAlias, address)
}

const getActiveSenderAliases = `-- name: GetActiveSenderAliases :many
SELECT allowed FROM senderaliasMap WHERE address = ? AND active = 'true'
`

func (q *Queries) GetActiveSenderAliases(ctx context.Context, address string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSenderAliases, address)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var allowed string
		if err := rows.Scan(&allowed); err != nil {
			return nil, err
		}
		items = append(items, allowed)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAliasRedirect = `-- name: GetAliasRedirect :one
SELECT goto FROM aliasMap WHERE ((address = ? AND etype = 'plain') OR (? LIKE address AND etype = 'pattern') OR (sqlc.arg(address) RLIKE address AND etype = 'regex')) AND active = 'true' LIMIT 1
`

type GetAliasRedirectParams struct {
	Address string `json:"address"`
}

func (q *Queries) GetAliasRedirect(ctx context.Context, arg GetAliasRedirectParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getAliasRedirect, arg.Address, arg.Address)
	var goto_ string
	err := row.Scan(&goto_)
	return goto_, err
}

const getAllActiveAliases = `-- name: GetAllActiveAliases :many
SELECT address, goto, etype FROM aliasMap WHERE active = 'true'
`

type GetAllActiveAliasesRow struct {
	Address string        `json:"address"`
	Goto    string        `json:"goto"`
	Etype   AliasmapEtype `json:"etype"`
}

func (q *Queries) GetAllActiveAliases(ctx context.Context) ([]GetAllActiveAliasesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActiveAliasesRow
	for rows.Next() {
		var i GetAllActiveAliasesRow
		if err := rows.Scan(&i.Address, &i.Goto, &i.Etype); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllActiveDomainAliases = `-- name: GetAllActiveDomainAliases :many
SELECT domain, goto, etype FROM aliasdomainMap WHERE active = 'true'
`

type GetAllActiveDomainAliasesRow struct {
	Domain string              `json:"domain"`
	Goto   string              `json:"goto"`
	Etype  AliasdomainmapEtype `json:"etype"`
}

func (q *Queries) GetAllActiveDomainAliases(ctx context.Context) ([]GetAllActiveDomainAliasesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveDomainAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActiveDomainAliasesRow
	for rows.Next() {
		var i GetAllActiveDomainAliasesRow
		if err := rows.Scan(&i.Domain, &i.Goto, &i.Etype); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllActiveUserAliases = `-- name: GetAllActiveUserAliases :many
SELECT user, goto, etype FROM aliasuserMap WHERE active = 'true'
`

type GetAllActiveUserAliasesRow struct {
	User  string            `json:"user"`
	Goto  string            `json:"goto"`
	Etype AliasusermapEtype `json:"etype"`
}

func (q *Queries) GetAllActiveUserAliases(ctx context.Context) ([]GetAllActiveUserAliasesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveUserAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActiveUserAliasesRow
	for rows.Next() {
		var i GetAllActiveUserAliasesRow
		if err := rows.Scan(&i.User, &i.Goto, &i.Etype); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllActiveWildcardAliases = `-- name: GetAllActiveWildcardAliases :many
SELECT address, goto FROM wildcardaliasMap WHERE active = 'true'
`

type GetAllActiveWildcardAliasesRow struct {
	Address string `json:"address"`
	Goto    string `json:"goto"`
}

func (q *Queries) GetAllActiveWildcardAliases(ctx context.Context) ([]GetAllActiveWildcardAliasesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveWildcardAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActiveWildcardAliasesRow
	for rows.Next() {
		var i GetAllActiveWildcardAliasesRow
		if err := rows.Scan(&i.Address, &i.Goto); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAliases = `-- name: GetAllAliases :many
SELECT address, goto, active, etype FROM aliasMap
`

func (q *Queries) GetAllAliases(ctx context.Context) ([]Aliasmap, error) {
	rows, err := q.db.QueryContext(ctx, getAllAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Aliasmap
	for rows.Next() {
		var i Aliasmap
		if err := rows.Scan(
			&i.Address,
			&i.Goto,
			&i.Active,
			&i.Etype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDomainAliases = `-- name: GetAllDomainAliases :many
SELECT domain, goto, active, etype FROM aliasdomainMap
`

func (q *Queries) GetAllDomainAliases(ctx context.Context) ([]Aliasdomainmap, error) {
	rows, err := q.db.QueryContext(ctx, getAllDomainAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Aliasdomainmap
	for rows.Next() {
		var i Aliasdomainmap
		if err := rows.Scan(
			&i.Domain,
			&i.Goto,
			&i.Active,
			&i.Etype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSenderAliases = `-- name: GetAllSenderAliases :many
SELECT allowed, active FROM senderaliasMap
`

type GetAllSenderAliasesRow struct {
	Allowed string               `json:"allowed"`
	Active  SenderaliasmapActive `json:"active"`
}

func (q *Queries) GetAllSenderAliases(ctx context.Context) ([]GetAllSenderAliasesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllSenderAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSenderAliasesRow
	for rows.Next() {
		var i GetAllSenderAliasesRow
		if err := rows.Scan(&i.Allowed, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserAliases = `-- name: GetAllUserAliases :many
SELECT user, goto, active, etype FROM aliasuserMap
`

func (q *Queries) GetAllUserAliases(ctx context.Context) ([]Aliasusermap, error) {
	rows, err := q.db.QueryContext(ctx, getAllUserAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Aliasusermap
	for rows.Next() {
		var i Aliasusermap
		if err := rows.Scan(
			&i.User,
			&i.Goto,
			&i.Active,
			&i.Etype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllWildcardAliases = `-- name: GetAllWildcardAliases :many
SELECT address, goto, active FROM wildcardaliasMap
`

func (q *Queries) GetAllWildcardAliases(ctx context.Context) ([]Wildcardaliasmap, error) {
	rows, err := q.db.QueryContext(ctx, getAllWildcardAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wildcardaliasmap
	for rows.Next() {
		var i Wildcardaliasmap
		if err := rows.Scan(&i.Address, &i.Goto, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomainAliasRedirect = `-- name: GetDomainAliasRedirect :one
SELECT goto FROM aliasdomainMap WHERE ((domain = ? AND etype = 'plain') OR (? LIKE domain AND etype = 'pattern') OR (sqlc.arg(domain) RLIKE domain AND etype = 'regex')) AND active = 'true' LIMIT 1
`

type GetDomainAliasRedirectParams struct {
	Domain string `json:"domain"`
}

func (q *Queries) GetDomainAliasRedirect(ctx context.Context, arg GetDomainAliasRedirectParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getDomainAliasRedirect, arg.Domain, arg.Domain)
	var goto_ string
	err := row.Scan(&goto_)
	return goto_, err
}

const getSenderAliases = `-- name: GetSenderAliases :many
SELECT allowed, active FROM senderaliasMap WHERE address = ?
`

type GetSenderAliasesRow struct {
	Allowed string               `json:"allowed"`
	Active  SenderaliasmapActive `json:"active"`
}

func (q *Queries) GetSenderAliases(ctx context.Context, address string) ([]GetSenderAliasesRow, error) {
	rows, err := q.db.QueryContext(ctx, getSenderAliases, address)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSenderAliasesRow
	for rows.Next() {
		var i GetSenderAliasesRow
		if err := rows.Scan(&i.Allowed, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAliasRedirect = `-- name: GetUserAliasRedirect :one
SELECT goto FROM aliasuserMap WHERE ((user = ? AND etype = 'plain') OR (? LIKE user AND etype = 'pattern') OR (sqlc.arg(user) RLIKE user AND etype = 'regex')) AND active = 'true' LIMIT 1
`

type GetUserAliasRedirectParams struct {
	User string `json:"user"`
}

func (q *Queries) GetUserAliasRedirect(ctx context.Context, arg GetUserAliasRedirectParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserAliasRedirect, arg.User, arg.User)
	var goto_ string
	err := row.Scan(&goto_)
	return goto_, err
}

const getWildcardAliasRedirect = `-- name: GetWildcardAliasRedirect :one
SELECT goto FROM wildcardaliasMap WHERE address = ? AND active = 'true' LIMIT 1
`

func (q *Queries) GetWildcardAliasRedirect(ctx context.Context, address string) (string, error) {
	row := q.db.QueryRowContext(ctx, getWildcardAliasRedirect, address)
	var goto_ string
	err := row.Scan(&goto_)
	return goto_, err
}

const removeAlias = `-- name: RemoveAlias :execresult
DELETE FROM aliasMap WHERE address = ?
`

func (q *Queries) RemoveAlias(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeAlias, address)
}

const removeDomainAlias = `-- name: RemoveDomainAlias :execresult
DELETE FROM aliasdomainMap WHERE domain = ?
`

func (q *Queries) RemoveDomainAlias(ctx context.Context, domain string) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeDomainAlias, domain)
}

const removeSenderAlias = `-- name: RemoveSenderAlias :execresult
DELETE FROM senderaliasMap WHERE address = ? AND allowed = ?
`

type RemoveSenderAliasParams struct {
	Address string `json:"address"`
	Allowed string `json:"allowed"`
}

func (q *Queries) RemoveSenderAlias(ctx context.Context, arg RemoveSenderAliasParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeSenderAlias, arg.Address, arg.Allowed)
}

const removeUserAlias = `-- name: RemoveUserAlias :execresult
DELETE FROM aliasuserMap WHERE user = ?
`

func (q *Queries) RemoveUserAlias(ctx context.Context, user string) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeUserAlias, user)
}

const removeWildcardAlias = `-- name: RemoveWildcardAlias :execresult
DELETE FROM wildcardaliasMap WHERE address = ?
`

func (q *Queries) RemoveWildcardAlias(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeWildcardAlias, address)
}
