// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: blocking.sql

package database

import (
	"context"
	"database/sql"
)

const block = `-- name: Block :execresult
INSERT INTO receiveBlockMap (address, access) VALUES (?, 'REJECT')
`

func (q *Queries) Block(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, block, address)
}

const createReport = `-- name: CreateReport :execresult
INSERT INTO receiveBlockReports (address, reporter, report) VALUES (?, ?, ?)
`

type CreateReportParams struct {
	Address  string `json:"address"`
	Reporter string `json:"reporter"`
	Report   string `json:"report"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReport, arg.Address, arg.Reporter, arg.Report)
}

const deleteReport = `-- name: DeleteReport :execresult
DELETE FROM receiveBlockReports WHERE address = ? AND reporter = ?
`

type DeleteReportParams struct {
	Address  string `json:"address"`
	Reporter string `json:"reporter"`
}

func (q *Queries) DeleteReport(ctx context.Context, arg DeleteReportParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteReport, arg.Address, arg.Reporter)
}

const getAllBlocks = `-- name: GetAllBlocks :many
SELECT address, access FROM receiveBlockMap
`

func (q *Queries) GetAllBlocks(ctx context.Context) ([]Receiveblockmap, error) {
	rows, err := q.db.QueryContext(ctx, getAllBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receiveblockmap
	for rows.Next() {
		var i Receiveblockmap
		if err := rows.Scan(&i.Address, &i.Access); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllReports = `-- name: GetAllReports :many
SELECT address, reporter, report FROM receiveBlockReports
`

func (q *Queries) GetAllReports(ctx context.Context) ([]Receiveblockreport, error) {
	rows, err := q.db.QueryContext(ctx, getAllReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receiveblockreport
	for rows.Next() {
		var i Receiveblockreport
		if err := rows.Scan(&i.Address, &i.Reporter, &i.Report); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlock = `-- name: GetBlock :one
SELECT access FROM receiveBlockMap WHERE address = ?
`

func (q *Queries) GetBlock(ctx context.Context, address string) (string, error) {
	row := q.db.QueryRowContext(ctx, getBlock, address)
	var access string
	err := row.Scan(&access)
	return access, err
}

const getReport = `-- name: GetReport :one
SELECT report FROM receiveBlockReports WHERE address = ? AND reporter = ? LIMIT 1
`

type GetReportParams struct {
	Address  string `json:"address"`
	Reporter string `json:"reporter"`
}

func (q *Queries) GetReport(ctx context.Context, arg GetReportParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getReport, arg.Address, arg.Reporter)
	var report string
	err := row.Scan(&report)
	return report, err
}

const getReportsOfAddress = `-- name: GetReportsOfAddress :many
SELECT reporter, report FROM receiveBlockReports WHERE address = ?
`

type GetReportsOfAddressRow struct {
	Reporter string `json:"reporter"`
	Report   string `json:"report"`
}

func (q *Queries) GetReportsOfAddress(ctx context.Context, address string) ([]GetReportsOfAddressRow, error) {
	rows, err := q.db.QueryContext(ctx, getReportsOfAddress, address)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportsOfAddressRow
	for rows.Next() {
		var i GetReportsOfAddressRow
		if err := rows.Scan(&i.Reporter, &i.Report); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsOfReporter = `-- name: GetReportsOfReporter :many
SELECT address, report FROM receiveBlockReports WHERE reporter = ?
`

type GetReportsOfReporterRow struct {
	Address string `json:"address"`
	Report  string `json:"report"`
}

func (q *Queries) GetReportsOfReporter(ctx context.Context, reporter string) ([]GetReportsOfReporterRow, error) {
	rows, err := q.db.QueryContext(ctx, getReportsOfReporter, reporter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportsOfReporterRow
	for rows.Next() {
		var i GetReportsOfReporterRow
		if err := rows.Scan(&i.Address, &i.Report); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblock = `-- name: Unblock :execresult
DELETE FROM receiveBlockMap WHERE address = ?
`

func (q *Queries) Unblock(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, unblock, address)
}
