// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: delegation.sql

package database

import (
	"context"
	"database/sql"
)

const addDelegateRoute = `-- name: AddDelegateRoute :execresult
INSERT INTO delegateRouteMap (address, delegate) VALUES (? , ?)
`

type AddDelegateRouteParams struct {
	Address  string `json:"address"`
	Delegate string `json:"delegate"`
}

func (q *Queries) AddDelegateRoute(ctx context.Context, arg AddDelegateRouteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addDelegateRoute, arg.Address, arg.Delegate)
}

const createDelegateAccount = `-- name: CreateDelegateAccount :execresult
INSERT INTO delegateMap (address, owner, auth, active) VALUES (?, ? , ?, 'false')
`

type CreateDelegateAccountParams struct {
	Address string `json:"address"`
	Owner   string `json:"owner"`
	Auth    string `json:"auth"`
}

func (q *Queries) CreateDelegateAccount(ctx context.Context, arg CreateDelegateAccountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDelegateAccount, arg.Address, arg.Owner, arg.Auth)
}

const deleteDelegateAccount = `-- name: DeleteDelegateAccount :execresult
DELETE FROM delegateMap WHERE address = ?
`

func (q *Queries) DeleteDelegateAccount(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteDelegateAccount, address)
}

const disableDelegateAccount = `-- name: DisableDelegateAccount :execresult
UPDATE delegateMap SET active = 'false' WHERE address = ?
`

func (q *Queries) DisableDelegateAccount(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, disableDelegateAccount, address)
}

const enableDelegateAccount = `-- name: EnableDelegateAccount :execresult
UPDATE delegateMap SET active = 'true' WHERE address = ?
`

func (q *Queries) EnableDelegateAccount(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, enableDelegateAccount, address)
}

const getAllDelegateAccounts = `-- name: GetAllDelegateAccounts :many
SELECT address, owner, auth, active FROM delegateMap
`

func (q *Queries) GetAllDelegateAccounts(ctx context.Context) ([]Delegatemap, error) {
	rows, err := q.db.QueryContext(ctx, getAllDelegateAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delegatemap
	for rows.Next() {
		var i Delegatemap
		if err := rows.Scan(
			&i.Address,
			&i.Owner,
			&i.Auth,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDelegateAccountsFor = `-- name: GetAllDelegateAccountsFor :many
SELECT address, owner, auth, active FROM delegateMap WHERE owner = ?
`

func (q *Queries) GetAllDelegateAccountsFor(ctx context.Context, owner string) ([]Delegatemap, error) {
	rows, err := q.db.QueryContext(ctx, getAllDelegateAccountsFor, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delegatemap
	for rows.Next() {
		var i Delegatemap
		if err := rows.Scan(
			&i.Address,
			&i.Owner,
			&i.Auth,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDelegateRoutes = `-- name: GetAllDelegateRoutes :many
SELECT address, delegate FROM delegateRouteMap
`

func (q *Queries) GetAllDelegateRoutes(ctx context.Context) ([]Delegateroutemap, error) {
	rows, err := q.db.QueryContext(ctx, getAllDelegateRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delegateroutemap
	for rows.Next() {
		var i Delegateroutemap
		if err := rows.Scan(&i.Address, &i.Delegate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDelegateAccount = `-- name: GetDelegateAccount :one
SELECT address, owner, auth, active FROM delegateMap WHERE address = ? LIMIT 1
`

func (q *Queries) GetDelegateAccount(ctx context.Context, address string) (Delegatemap, error) {
	row := q.db.QueryRowContext(ctx, getDelegateAccount, address)
	var i Delegatemap
	err := row.Scan(
		&i.Address,
		&i.Owner,
		&i.Auth,
		&i.Active,
	)
	return i, err
}

const getDelegateAccountAuth = `-- name: GetDelegateAccountAuth :one
SELECT auth FROM delegateMap WHERE address = ? AND active = 'true' LIMIT 1
`

func (q *Queries) GetDelegateAccountAuth(ctx context.Context, address string) (string, error) {
	row := q.db.QueryRowContext(ctx, getDelegateAccountAuth, address)
	var auth string
	err := row.Scan(&auth)
	return auth, err
}

const getDelegateRoute = `-- name: GetDelegateRoute :one
SELECT delegate FROM delegateRouteMap WHERE address = ? LIMIT 1
`

func (q *Queries) GetDelegateRoute(ctx context.Context, address string) (string, error) {
	row := q.db.QueryRowContext(ctx, getDelegateRoute, address)
	var delegate string
	err := row.Scan(&delegate)
	return delegate, err
}

const removeDelegateRoute = `-- name: RemoveDelegateRoute :execresult
DELETE FROM delegateRouteMap WHERE address = ?
`

func (q *Queries) RemoveDelegateRoute(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeDelegateRoute, address)
}

const updateDelegateAccountAuth = `-- name: UpdateDelegateAccountAuth :execresult
UPDATE delegateMap SET auth = ? WHERE address = ?
`

type UpdateDelegateAccountAuthParams struct {
	Auth    string `json:"auth"`
	Address string `json:"address"`
}

func (q *Queries) UpdateDelegateAccountAuth(ctx context.Context, arg UpdateDelegateAccountAuthParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateDelegateAccountAuth, arg.Auth, arg.Address)
}
