// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: domains.sql

package database

import (
	"context"
	"database/sql"
)

const addDomain = `-- name: AddDomain :execresult
INSERT INTO domainMap (domain, active) VALUES (?, 'false')
`

func (q *Queries) AddDomain(ctx context.Context, domain string) (sql.Result, error) {
	return q.db.ExecContext(ctx, addDomain, domain)
}

const addSMTPSendRoute = `-- name: AddSMTPSendRoute :execresult
INSERT INTO smtpIngestMap (address, start) VALUES (?, ?)
`

type AddSMTPSendRouteParams struct {
	Address string         `json:"address"`
	Start   sql.NullString `json:"start"`
}

func (q *Queries) AddSMTPSendRoute(ctx context.Context, arg AddSMTPSendRouteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addSMTPSendRoute, arg.Address, arg.Start)
}

const addSMTPSendRouteDelegated = `-- name: AddSMTPSendRouteDelegated :execresult
INSERT INTO smtpIngestMap (address, start) VALUES (?, NULL)
`

func (q *Queries) AddSMTPSendRouteDelegated(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, addSMTPSendRouteDelegated, address)
}

const disableDomain = `-- name: DisableDomain :execresult
UPDATE domainMap SET active = 'false' WHERE domain = ?
`

func (q *Queries) DisableDomain(ctx context.Context, domain string) (sql.Result, error) {
	return q.db.ExecContext(ctx, disableDomain, domain)
}

const enableDomain = `-- name: EnableDomain :execresult
UPDATE domainMap SET active = 'true' WHERE domain = ?
`

func (q *Queries) EnableDomain(ctx context.Context, domain string) (sql.Result, error) {
	return q.db.ExecContext(ctx, enableDomain, domain)
}

const getAllActiveDomains = `-- name: GetAllActiveDomains :many
SELECT domain FROM domainMap WHERE active = 'true'
`

func (q *Queries) GetAllActiveDomains(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var domain string
		if err := rows.Scan(&domain); err != nil {
			return nil, err
		}
		items = append(items, domain)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDomains = `-- name: GetAllDomains :many
SELECT domain, active FROM domainMap
`

func (q *Queries) GetAllDomains(ctx context.Context) ([]Domainmap, error) {
	rows, err := q.db.QueryContext(ctx, getAllDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domainmap
	for rows.Next() {
		var i Domainmap
		if err := rows.Scan(&i.Domain, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllInactiveDomains = `-- name: GetAllInactiveDomains :many
SELECT domain FROM domainMap WHERE active <> 'true'
`

func (q *Queries) GetAllInactiveDomains(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllInactiveDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var domain string
		if err := rows.Scan(&domain); err != nil {
			return nil, err
		}
		items = append(items, domain)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSMTPSendRoutes = `-- name: GetAllSMTPSendRoutes :many
SELECT address, start FROM smtpIngestMap
`

func (q *Queries) GetAllSMTPSendRoutes(ctx context.Context) ([]Smtpingestmap, error) {
	rows, err := q.db.QueryContext(ctx, getAllSMTPSendRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Smtpingestmap
	for rows.Next() {
		var i Smtpingestmap
		if err := rows.Scan(&i.Address, &i.Start); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSMTPSendRoutesDelegated = `-- name: GetAllSMTPSendRoutesDelegated :many
SELECT address, start FROM smtpIngestMap WHERE start IS NULL
`

func (q *Queries) GetAllSMTPSendRoutesDelegated(ctx context.Context) ([]Smtpingestmap, error) {
	rows, err := q.db.QueryContext(ctx, getAllSMTPSendRoutesDelegated)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Smtpingestmap
	for rows.Next() {
		var i Smtpingestmap
		if err := rows.Scan(&i.Address, &i.Start); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSMTPSendRoutesNonDelegated = `-- name: GetAllSMTPSendRoutesNonDelegated :many
SELECT address, start FROM smtpIngestMap WHERE start IS NOT NULL
`

func (q *Queries) GetAllSMTPSendRoutesNonDelegated(ctx context.Context) ([]Smtpingestmap, error) {
	rows, err := q.db.QueryContext(ctx, getAllSMTPSendRoutesNonDelegated)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Smtpingestmap
	for rows.Next() {
		var i Smtpingestmap
		if err := rows.Scan(&i.Address, &i.Start); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomain = `-- name: GetDomain :one
SELECT domain, active FROM domainMap WHERE domain = ? LIMIT 1
`

func (q *Queries) GetDomain(ctx context.Context, domain string) (Domainmap, error) {
	row := q.db.QueryRowContext(ctx, getDomain, domain)
	var i Domainmap
	err := row.Scan(&i.Domain, &i.Active)
	return i, err
}

const getSMTPSendRoute = `-- name: GetSMTPSendRoute :one
SELECT start FROM smtpIngestMap WHERE address = ? LIMIT 1
`

func (q *Queries) GetSMTPSendRoute(ctx context.Context, address string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getSMTPSendRoute, address)
	var start sql.NullString
	err := row.Scan(&start)
	return start, err
}

const removeDomain = `-- name: RemoveDomain :execresult
DELETE FROM domainMap WHERE domain = ?
`

func (q *Queries) RemoveDomain(ctx context.Context, domain string) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeDomain, domain)
}

const removeSMTPSendRoute = `-- name: RemoveSMTPSendRoute :execresult
DELETE FROM smtpIngestMap WHERE address = ?
`

func (q *Queries) RemoveSMTPSendRoute(ctx context.Context, address string) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeSMTPSendRoute, address)
}
