// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mailboxes.sql

package database

import (
	"context"
	"database/sql"
)

const addMailbox = `-- name: AddMailbox :execresult
INSERT INTO mailbox (username, maildir, quota, active) VALUES (?, ?, ?, 'false')
`

type AddMailboxParams struct {
	Username string `json:"username"`
	Maildir  string `json:"maildir"`
	Quota    int64  `json:"quota"`
}

func (q *Queries) AddMailbox(ctx context.Context, arg AddMailboxParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addMailbox, arg.Username, arg.Maildir, arg.Quota)
}

const changeMailboxMaildir = `-- name: ChangeMailboxMaildir :execresult
UPDATE mailbox SET maildir = ? WHERE username = ?
`

type ChangeMailboxMaildirParams struct {
	Maildir  string `json:"maildir"`
	Username string `json:"username"`
}

func (q *Queries) ChangeMailboxMaildir(ctx context.Context, arg ChangeMailboxMaildirParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, changeMailboxMaildir, arg.Maildir, arg.Username)
}

const changeMailboxQuota = `-- name: ChangeMailboxQuota :execresult
UPDATE mailbox SET quota = ? WHERE username = ?
`

type ChangeMailboxQuotaParams struct {
	Maildir  int64  `json:"maildir"`
	Username string `json:"username"`
}

func (q *Queries) ChangeMailboxQuota(ctx context.Context, arg ChangeMailboxQuotaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, changeMailboxQuota, arg.Maildir, arg.Username)
}

const deactivateMailbox = `-- name: DeactivateMailbox :execresult
UPDATE mailbox SET active = 'false' WHERE username = ?
`

func (q *Queries) DeactivateMailbox(ctx context.Context, username string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deactivateMailbox, username)
}

const disableMailbox = `-- name: DisableMailbox :execresult
UPDATE mailbox SET active = 'disabled' WHERE username = ?
`

func (q *Queries) DisableMailbox(ctx context.Context, username string) (sql.Result, error) {
	return q.db.ExecContext(ctx, disableMailbox, username)
}

const enableMailbox = `-- name: EnableMailbox :execresult
UPDATE mailbox SET active = 'true' WHERE username = ?
`

func (q *Queries) EnableMailbox(ctx context.Context, username string) (sql.Result, error) {
	return q.db.ExecContext(ctx, enableMailbox, username)
}

const getAllActiveMailboxes = `-- name: GetAllActiveMailboxes :many
SELECT username, maildir, quota FROM mailbox WHERE active = 'true' OR active = 'disabled'
`

type GetAllActiveMailboxesRow struct {
	Username string `json:"username"`
	Maildir  string `json:"maildir"`
	Quota    int64  `json:"quota"`
}

func (q *Queries) GetAllActiveMailboxes(ctx context.Context) ([]GetAllActiveMailboxesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveMailboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActiveMailboxesRow
	for rows.Next() {
		var i GetAllActiveMailboxesRow
		if err := rows.Scan(&i.Username, &i.Maildir, &i.Quota); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllEnabledMailboxes = `-- name: GetAllEnabledMailboxes :many
SELECT username, maildir, quota FROM mailbox WHERE active = 'true'
`

type GetAllEnabledMailboxesRow struct {
	Username string `json:"username"`
	Maildir  string `json:"maildir"`
	Quota    int64  `json:"quota"`
}

func (q *Queries) GetAllEnabledMailboxes(ctx context.Context) ([]GetAllEnabledMailboxesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEnabledMailboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEnabledMailboxesRow
	for rows.Next() {
		var i GetAllEnabledMailboxesRow
		if err := rows.Scan(&i.Username, &i.Maildir, &i.Quota); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllInactiveMailboxes = `-- name: GetAllInactiveMailboxes :many
SELECT username, maildir, quota FROM mailbox WHERE active <> 'true'
`

type GetAllInactiveMailboxesRow struct {
	Username string `json:"username"`
	Maildir  string `json:"maildir"`
	Quota    int64  `json:"quota"`
}

func (q *Queries) GetAllInactiveMailboxes(ctx context.Context) ([]GetAllInactiveMailboxesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllInactiveMailboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllInactiveMailboxesRow
	for rows.Next() {
		var i GetAllInactiveMailboxesRow
		if err := rows.Scan(&i.Username, &i.Maildir, &i.Quota); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMailboxes = `-- name: GetAllMailboxes :many
SELECT username, maildir, quota, active FROM mailbox
`

func (q *Queries) GetAllMailboxes(ctx context.Context) ([]Mailbox, error) {
	rows, err := q.db.QueryContext(ctx, getAllMailboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mailbox
	for rows.Next() {
		var i Mailbox
		if err := rows.Scan(
			&i.Username,
			&i.Maildir,
			&i.Quota,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMailbox = `-- name: GetMailbox :one
SELECT username, maildir, quota, active FROM mailbox WHERE username = ? LIMIT 1
`

func (q *Queries) GetMailbox(ctx context.Context, username string) (Mailbox, error) {
	row := q.db.QueryRowContext(ctx, getMailbox, username)
	var i Mailbox
	err := row.Scan(
		&i.Username,
		&i.Maildir,
		&i.Quota,
		&i.Active,
	)
	return i, err
}

const getMailboxMaildir = `-- name: GetMailboxMaildir :one
SELECT maildir FROM mailbox WHERE username = ? AND (active = 'true' OR active = 'disabled') LIMIT 1
`

func (q *Queries) GetMailboxMaildir(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMailboxMaildir, username)
	var maildir string
	err := row.Scan(&maildir)
	return maildir, err
}

const getMailboxQuota = `-- name: GetMailboxQuota :one
SELECT quota FROM mailbox WHERE username = ? AND (active = 'true' OR active = 'disabled') LIMIT 1
`

func (q *Queries) GetMailboxQuota(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMailboxQuota, username)
	var quota int64
	err := row.Scan(&quota)
	return quota, err
}

const removeMailbox = `-- name: RemoveMailbox :execresult
DELETE FROM mailbox WHERE username = ?
`

func (q *Queries) RemoveMailbox(ctx context.Context, username string) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeMailbox, username)
}
