// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type AliasdomainmapActive string

const (
	AliasdomainmapActiveFalse    AliasdomainmapActive = "false"
	AliasdomainmapActiveTrue     AliasdomainmapActive = "true"
	AliasdomainmapActiveCatchAll AliasdomainmapActive = "catch_all"
)

func (e *AliasdomainmapActive) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AliasdomainmapActive(s)
	case string:
		*e = AliasdomainmapActive(s)
	default:
		return fmt.Errorf("unsupported scan type for AliasdomainmapActive: %T", src)
	}
	return nil
}

type NullAliasdomainmapActive struct {
	AliasdomainmapActive AliasdomainmapActive `json:"aliasdomainmap_active"`
	Valid                bool                 `json:"valid"` // Valid is true if AliasdomainmapActive is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAliasdomainmapActive) Scan(value interface{}) error {
	if value == nil {
		ns.AliasdomainmapActive, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AliasdomainmapActive.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAliasdomainmapActive) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AliasdomainmapActive), nil
}

type AliasdomainmapEtype string

const (
	AliasdomainmapEtypePlain   AliasdomainmapEtype = "plain"
	AliasdomainmapEtypePattern AliasdomainmapEtype = "pattern"
	AliasdomainmapEtypeRegex   AliasdomainmapEtype = "regex"
)

func (e *AliasdomainmapEtype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AliasdomainmapEtype(s)
	case string:
		*e = AliasdomainmapEtype(s)
	default:
		return fmt.Errorf("unsupported scan type for AliasdomainmapEtype: %T", src)
	}
	return nil
}

type NullAliasdomainmapEtype struct {
	AliasdomainmapEtype AliasdomainmapEtype `json:"aliasdomainmap_etype"`
	Valid               bool                `json:"valid"` // Valid is true if AliasdomainmapEtype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAliasdomainmapEtype) Scan(value interface{}) error {
	if value == nil {
		ns.AliasdomainmapEtype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AliasdomainmapEtype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAliasdomainmapEtype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AliasdomainmapEtype), nil
}

type AliasmapActive string

const (
	AliasmapActiveFalse AliasmapActive = "false"
	AliasmapActiveTrue  AliasmapActive = "true"
)

func (e *AliasmapActive) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AliasmapActive(s)
	case string:
		*e = AliasmapActive(s)
	default:
		return fmt.Errorf("unsupported scan type for AliasmapActive: %T", src)
	}
	return nil
}

type NullAliasmapActive struct {
	AliasmapActive AliasmapActive `json:"aliasmap_active"`
	Valid          bool           `json:"valid"` // Valid is true if AliasmapActive is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAliasmapActive) Scan(value interface{}) error {
	if value == nil {
		ns.AliasmapActive, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AliasmapActive.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAliasmapActive) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AliasmapActive), nil
}

type AliasmapEtype string

const (
	AliasmapEtypePlain   AliasmapEtype = "plain"
	AliasmapEtypePattern AliasmapEtype = "pattern"
	AliasmapEtypeRegex   AliasmapEtype = "regex"
)

func (e *AliasmapEtype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AliasmapEtype(s)
	case string:
		*e = AliasmapEtype(s)
	default:
		return fmt.Errorf("unsupported scan type for AliasmapEtype: %T", src)
	}
	return nil
}

type NullAliasmapEtype struct {
	AliasmapEtype AliasmapEtype `json:"aliasmap_etype"`
	Valid         bool          `json:"valid"` // Valid is true if AliasmapEtype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAliasmapEtype) Scan(value interface{}) error {
	if value == nil {
		ns.AliasmapEtype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AliasmapEtype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAliasmapEtype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AliasmapEtype), nil
}

type AliasusermapActive string

const (
	AliasusermapActiveFalse    AliasusermapActive = "false"
	AliasusermapActiveTrue     AliasusermapActive = "true"
	AliasusermapActiveCatchAll AliasusermapActive = "catch_all"
)

func (e *AliasusermapActive) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AliasusermapActive(s)
	case string:
		*e = AliasusermapActive(s)
	default:
		return fmt.Errorf("unsupported scan type for AliasusermapActive: %T", src)
	}
	return nil
}

type NullAliasusermapActive struct {
	AliasusermapActive AliasusermapActive `json:"aliasusermap_active"`
	Valid              bool               `json:"valid"` // Valid is true if AliasusermapActive is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAliasusermapActive) Scan(value interface{}) error {
	if value == nil {
		ns.AliasusermapActive, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AliasusermapActive.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAliasusermapActive) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AliasusermapActive), nil
}

type AliasusermapEtype string

const (
	AliasusermapEtypePlain   AliasusermapEtype = "plain"
	AliasusermapEtypePattern AliasusermapEtype = "pattern"
	AliasusermapEtypeRegex   AliasusermapEtype = "regex"
)

func (e *AliasusermapEtype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AliasusermapEtype(s)
	case string:
		*e = AliasusermapEtype(s)
	default:
		return fmt.Errorf("unsupported scan type for AliasusermapEtype: %T", src)
	}
	return nil
}

type NullAliasusermapEtype struct {
	AliasusermapEtype AliasusermapEtype `json:"aliasusermap_etype"`
	Valid             bool              `json:"valid"` // Valid is true if AliasusermapEtype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAliasusermapEtype) Scan(value interface{}) error {
	if value == nil {
		ns.AliasusermapEtype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AliasusermapEtype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAliasusermapEtype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AliasusermapEtype), nil
}

type DelegatemapActive string

const (
	DelegatemapActiveFalse DelegatemapActive = "false"
	DelegatemapActiveTrue  DelegatemapActive = "true"
)

func (e *DelegatemapActive) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DelegatemapActive(s)
	case string:
		*e = DelegatemapActive(s)
	default:
		return fmt.Errorf("unsupported scan type for DelegatemapActive: %T", src)
	}
	return nil
}

type NullDelegatemapActive struct {
	DelegatemapActive DelegatemapActive `json:"delegatemap_active"`
	Valid             bool              `json:"valid"` // Valid is true if DelegatemapActive is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDelegatemapActive) Scan(value interface{}) error {
	if value == nil {
		ns.DelegatemapActive, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DelegatemapActive.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDelegatemapActive) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DelegatemapActive), nil
}

type DomainmapActive string

const (
	DomainmapActiveFalse DomainmapActive = "false"
	DomainmapActiveTrue  DomainmapActive = "true"
)

func (e *DomainmapActive) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DomainmapActive(s)
	case string:
		*e = DomainmapActive(s)
	default:
		return fmt.Errorf("unsupported scan type for DomainmapActive: %T", src)
	}
	return nil
}

type NullDomainmapActive struct {
	DomainmapActive DomainmapActive `json:"domainmap_active"`
	Valid           bool            `json:"valid"` // Valid is true if DomainmapActive is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDomainmapActive) Scan(value interface{}) error {
	if value == nil {
		ns.DomainmapActive, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DomainmapActive.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDomainmapActive) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DomainmapActive), nil
}

type MailboxActive string

const (
	MailboxActiveFalse    MailboxActive = "false"
	MailboxActiveDisabled MailboxActive = "disabled"
	MailboxActiveTrue     MailboxActive = "true"
)

func (e *MailboxActive) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MailboxActive(s)
	case string:
		*e = MailboxActive(s)
	default:
		return fmt.Errorf("unsupported scan type for MailboxActive: %T", src)
	}
	return nil
}

type NullMailboxActive struct {
	MailboxActive MailboxActive `json:"mailbox_active"`
	Valid         bool          `json:"valid"` // Valid is true if MailboxActive is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMailboxActive) Scan(value interface{}) error {
	if value == nil {
		ns.MailboxActive, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MailboxActive.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMailboxActive) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MailboxActive), nil
}

type MailmasterActive string

const (
	MailmasterActiveFalse MailmasterActive = "false"
	MailmasterActiveTrue  MailmasterActive = "true"
)

func (e *MailmasterActive) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MailmasterActive(s)
	case string:
		*e = MailmasterActive(s)
	default:
		return fmt.Errorf("unsupported scan type for MailmasterActive: %T", src)
	}
	return nil
}

type NullMailmasterActive struct {
	MailmasterActive MailmasterActive `json:"mailmaster_active"`
	Valid            bool             `json:"valid"` // Valid is true if MailmasterActive is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMailmasterActive) Scan(value interface{}) error {
	if value == nil {
		ns.MailmasterActive, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MailmasterActive.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMailmasterActive) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MailmasterActive), nil
}

type MailshadowAllowPwdChng string

const (
	MailshadowAllowPwdChngFalse MailshadowAllowPwdChng = "false"
	MailshadowAllowPwdChngTrue  MailshadowAllowPwdChng = "true"
)

func (e *MailshadowAllowPwdChng) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MailshadowAllowPwdChng(s)
	case string:
		*e = MailshadowAllowPwdChng(s)
	default:
		return fmt.Errorf("unsupported scan type for MailshadowAllowPwdChng: %T", src)
	}
	return nil
}

type NullMailshadowAllowPwdChng struct {
	MailshadowAllowPwdChng MailshadowAllowPwdChng `json:"mailshadow_allow_pwd_chng"`
	Valid                  bool                   `json:"valid"` // Valid is true if MailshadowAllowPwdChng is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMailshadowAllowPwdChng) Scan(value interface{}) error {
	if value == nil {
		ns.MailshadowAllowPwdChng, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MailshadowAllowPwdChng.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMailshadowAllowPwdChng) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MailshadowAllowPwdChng), nil
}

type ReceiveprotectmapActive string

const (
	ReceiveprotectmapActiveFalse ReceiveprotectmapActive = "false"
	ReceiveprotectmapActiveTrue  ReceiveprotectmapActive = "true"
)

func (e *ReceiveprotectmapActive) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReceiveprotectmapActive(s)
	case string:
		*e = ReceiveprotectmapActive(s)
	default:
		return fmt.Errorf("unsupported scan type for ReceiveprotectmapActive: %T", src)
	}
	return nil
}

type NullReceiveprotectmapActive struct {
	ReceiveprotectmapActive ReceiveprotectmapActive `json:"receiveprotectmap_active"`
	Valid                   bool                    `json:"valid"` // Valid is true if ReceiveprotectmapActive is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReceiveprotectmapActive) Scan(value interface{}) error {
	if value == nil {
		ns.ReceiveprotectmapActive, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReceiveprotectmapActive.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReceiveprotectmapActive) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReceiveprotectmapActive), nil
}

type SenderaliasmapActive string

const (
	SenderaliasmapActiveFalse SenderaliasmapActive = "false"
	SenderaliasmapActiveTrue  SenderaliasmapActive = "true"
)

func (e *SenderaliasmapActive) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SenderaliasmapActive(s)
	case string:
		*e = SenderaliasmapActive(s)
	default:
		return fmt.Errorf("unsupported scan type for SenderaliasmapActive: %T", src)
	}
	return nil
}

type NullSenderaliasmapActive struct {
	SenderaliasmapActive SenderaliasmapActive `json:"senderaliasmap_active"`
	Valid                bool                 `json:"valid"` // Valid is true if SenderaliasmapActive is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSenderaliasmapActive) Scan(value interface{}) error {
	if value == nil {
		ns.SenderaliasmapActive, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SenderaliasmapActive.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSenderaliasmapActive) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SenderaliasmapActive), nil
}

type WildcardaliasmapActive string

const (
	WildcardaliasmapActiveFalse WildcardaliasmapActive = "false"
	WildcardaliasmapActiveTrue  WildcardaliasmapActive = "true"
)

func (e *WildcardaliasmapActive) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WildcardaliasmapActive(s)
	case string:
		*e = WildcardaliasmapActive(s)
	default:
		return fmt.Errorf("unsupported scan type for WildcardaliasmapActive: %T", src)
	}
	return nil
}

type NullWildcardaliasmapActive struct {
	WildcardaliasmapActive WildcardaliasmapActive `json:"wildcardaliasmap_active"`
	Valid                  bool                   `json:"valid"` // Valid is true if WildcardaliasmapActive is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWildcardaliasmapActive) Scan(value interface{}) error {
	if value == nil {
		ns.WildcardaliasmapActive, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WildcardaliasmapActive.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWildcardaliasmapActive) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WildcardaliasmapActive), nil
}

type Aliasdomainmap struct {
	Domain string               `json:"domain"`
	Goto   string               `json:"goto"`
	Active AliasdomainmapActive `json:"active"`
	Etype  AliasdomainmapEtype  `json:"etype"`
}

type Aliasmap struct {
	Address string         `json:"address"`
	Goto    string         `json:"goto"`
	Active  AliasmapActive `json:"active"`
	Etype   AliasmapEtype  `json:"etype"`
}

type Aliasusermap struct {
	User   string             `json:"user"`
	Goto   string             `json:"goto"`
	Active AliasusermapActive `json:"active"`
	Etype  AliasusermapEtype  `json:"etype"`
}

type Delegatemap struct {
	Address string            `json:"address"`
	Owner   string            `json:"owner"`
	Auth    string            `json:"auth"`
	Active  DelegatemapActive `json:"active"`
}

type Delegateroutemap struct {
	Address  string `json:"address"`
	Delegate string `json:"delegate"`
}

type Domainmap struct {
	Domain string          `json:"domain"`
	Active DomainmapActive `json:"active"`
}

type Mailbox struct {
	Username string        `json:"username"`
	Maildir  string        `json:"maildir"`
	Quota    int64         `json:"quota"`
	Active   MailboxActive `json:"active"`
}

type Mailmaster struct {
	Username string           `json:"username"`
	Password string           `json:"password"`
	Active   MailmasterActive `json:"active"`
}

type Mailshadow struct {
	Username     string                 `json:"username"`
	Password     string                 `json:"password"`
	AllowPwdChng MailshadowAllowPwdChng `json:"allow_pwd_chng"`
}

type Receiveblockmap struct {
	Address string `json:"address"`
	Access  string `json:"access"`
}

type Receiveblockreport struct {
	Address  string `json:"address"`
	Reporter string `json:"reporter"`
	Report   string `json:"report"`
}

type Receiveprotectmap struct {
	Address string                  `json:"address"`
	Access  string                  `json:"access"`
	Active  ReceiveprotectmapActive `json:"active"`
}

type Senderaliasmap struct {
	Address string               `json:"address"`
	Allowed string               `json:"allowed"`
	Active  SenderaliasmapActive `json:"active"`
}

type Smtpingestmap struct {
	Address string         `json:"address"`
	Start   sql.NullString `json:"start"`
}

type Wildcardaliasmap struct {
	Address string                 `json:"address"`
	Goto    string                 `json:"goto"`
	Active  WildcardaliasmapActive `json:"active"`
}
